
version: 2

sources:
  - name: staging
    description: > 
      raw data extracted from aneel website and first stored in datalake
    schema: data_warehouse_staging
    loader: bigquery

    tables:
      - name: stg_componentes_tarifarias
        description: "data from staging model"
        columns:
          - name: id
            description: >
              Primary key.
            data_type: int
          - name: dat_geracao_conjunto_dados
            description: >
              Date of automatic load processing at the time of dataset generation for publication.
            data_type: date
          - name: dsc_resolucao_homologatoria
            description: >
              Information about the number and date of the Homologatory Resolution.
            data_type: string
          - name: sig_nome_agente
            description: >
              Abbreviation of the name of Agents regulated by ANEEL.
            data_type: string
          - name: num_cpf_cnpj
            description: >
              CNPJ or CPF number of the audited agent (organization).
            data_type: string
          - name: dat_inicio_vigencia
            description: >
              Information about the start date of tariff validity.
            data_type: date
          - name: dat_fim_vigencia
            description: >
              Information about the end date of tariff validity.
            data_type: date
          - name: dsc_base_tarifaria
            description: >
              Tariff of Application, Economic Base, and CVA. 
              The Tariff of Application is used by the distributor for billing consumers, generators, and distributors, as stated in the Homologatory Resolution. 
              The Economic Base and CVA are used strictly for tariff calculations.
            data_type: string
          - name: dsc_sub_grupo_tarifario
            description: >
              Grouping of consumer units according to tariff groups: A1 (≥230 kV), A2 (88 kV to 138 kV), A3 (69 kV), A3a (30 kV to 44 kV), A4 (2.3 kV to 25 kV), 
              AS (underground), B1 (residential), B2 (rural), B3 (other classes), B4 (public lighting).
            data_type: string
          - name: dsc_modalidade_tarifaria
            description: >
              Set of tariffs applicable to energy consumption and demand components, as defined by Normative Resolution No. 1000/2021: 
              conventional; time-based (green and blue), white, prepaid, generation, and distribution.
            data_type: string
          - name: dsc_classe_consumidor
            description: >
              Classification of consumer units according to the purpose of energy use: 
              residential; rural; public lighting; and not applicable (industrial; commerce, services, and others; public power; public service; and self-consumption).
            data_type: string
          - name: dsc_sub_classe_consumidor
            description: >
              Classification of consumer units according to the purpose of energy use: 
              residential; rural; public lighting; and not applicable (industrial; commerce, services, and others; public power; public service; and self-consumption).
            data_type: string
          - name: dsc_detalhe_consumidor
            description: >
              Complementary set of variables used in defining tariffs based on application criteria or the universe of eligible consumers.
            data_type: string
          - name: dsc_posto_tarifario
            description: >
              Identification of the tariff period, defined as hourly intervals for differentiated tariff application throughout the day, as per Normative Resolution No. 1000/2021.
            data_type: string
          - name: dsc_unidade
            description: >
              Tariff unit, according to the applicable electrical quantity, which can be R$/kW and R$/MWh for TUSD and R$/MWh for TE.
            data_type: string
          - name: sig_nome_agente_acessante
            description: >
              Applicable in cases of nominal tariffs, specifically applicable to a user (distributor, consumer unit, or generator). The abbreviation is as registered in ANEEL's agent registry. Example: AmE, CEMIG-D, EMT, DCELT, CERFOX, etc.
            data_type: string
          - name: dsc_componente_tarifario
            description: >
              Description of the tariff component as: 
              "Components of the Tariff for Use of the Distribution System - TUSD (Tarifas de Uso do Sistema de Distribuição) and 
              the Energy Tariff - TE (Tarifas de Energia)."
            data_type: string
          - name: vlw_componente_tarifario
            description: >
              Value of the TE and TUSD components according to DscUnidade.
            data_type: float