name: 'aneel_dw'
version: '1.0.0'

profile: 'aneel_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  aneel_dw:
    staging:
      +schema: staging
      +materialized: table
      +tags: ['stg', 'aneel']
    
    dimensions:
      +schema: dimensions
      +materialized: table
      +tags: ['dim', 'aneel']

    facts:
      +schema: facts
      +materialized: table
      +tags: ['fct', 'aneel']